[build]
  command = "npm run build"
  publish = "_dist/"
  functions = "functions/"

[dev]
  framework = "#custom"
  command = "npm run dev"
  targetPort = 4000
  publish = "_dist/"
  autoLaunch = false

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/search-api/*"
  to = "http://v39241.php-friends.de:9200/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth-api/*"
  to = "https://drupal.admin.fortepan.hu"
  status = 200
  force = true

[[redirects]]
  from = "/photos/*"
  to = "https://fortepan.download/_photo/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/hu/"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/hu/user/*"
  to = "/"
  status = 200
  force = true

[[redirects]]
  from = "/en/user/*"
  to = "/en/"
  status = 200
  force = true

[[redirects]]
  from = "/m/*"
  to = "http://fortepan.hu/m/:splat"
  status = 200
  force = true