[build]
  command = "npm run build"
  publish = "_dist/"
  functions = "functions/"

[dev]
  command = "npm run dev"
  targetPort = 4000
  publish = "_dist/"

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/search-api/*"
  to = "http://v39241.php-friends.de:9200/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/auth-api/*"
  to = "http://admin.fortepan.hu:8080/:splat?_format=json"
  status = 200
  force = true

[[redirects]]
  from = "/photos/*"
  to = "https://fortepan.download/_photo/display/:splat"
  status = 200
  force = true