backend:
  name: git-gateway
  branch: master
media_folder: "/src/static/uploads"
public_folder: "/static/uploads"
locale: "hu"
collections:
  - name: "settings" # Used in routes, e.g., /admin/collections/blog
    label: "Settings" # Used in the UI
    files:
      - name: "config"
        label: "Config"
        file: "/src/data/cmsConfig.json"
        fields: # The fields for each document, usually in front matter
          - { label: Start Date, name: latestDate, widget: date, comment: 'This is a multiline\ncomment' }
