---
label: cmsConfig
hide_body: true
fields:
- name: latestDate
  type: datetime
  label: Friss dátum
  description: A Friss oldalon ettől a dátumtól kezdődik a képek listázása.
  config:
    required: true
    date_format: ''
    time_format: 
    display_utc: true
    export_format: ''
pages:
- src/data/cmsConfig.json
